server:
  port: ${VSPH_DEV_CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: vsph-config-server
  cloud:
    config:
      token:
    vault:
      uri: http://localhost:${VSPH_DEV_VAULT_PORT}
  config:
    import: optional:vault://
