version: '3.8'

name: moonsphere-infra

services:
  msph-config-server:
    container_name: msph-config-server
    ports:
      - '${ENV_DOCKER_MSPH_CONFIG_SERVER_PORT}:8888'
    build:
      context: ./msph-config-server
      dockerfile: Dockerfile
      args:
        - 'OPEN_PORT=8888'
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_SPRING_CONFIG_USERNAME=${ENV_DOCKER_MSPH_SPRING_CONFIG_USERNAME}'
      - 'MSPH_SPRING_CONFIG_PASSWORD=${ENV_DOCKER_MSPH_SPRING_CONFIG_PASSWORD}'
      - 'ENV_MSPH_SPRING_CONFIG_REPO_USERNAME=${ENV_MSPH_SPRING_CONFIG_REPO_USERNAME}'
      - 'ENV_MSPH_SPRING_CONFIG_REPO_TOKEN=${ENV_MSPH_SPRING_CONFIG_REPO_TOKEN}'

  msph-discovery-server:
    container_name: msph-discovery-server
    ports:
      - '${ENV_DOCKER_MSPH_DISCOVERY_SERVER_PORT}:8761'
    build:
      context: ./msph-discovery-server
      dockerfile: Dockerfile
      args:
        - 'OPEN_PORT=8761'
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_DOCKER_EUREKA_PORT=8761'
      - 'MSPH_SPRING_CONFIG_USERNAME=${ENV_DOCKER_MSPH_SPRING_CONFIG_USERNAME}'
      - 'MSPH_SPRING_CONFIG_PASSWORD=${ENV_DOCKER_MSPH_SPRING_CONFIG_PASSWORD}'
      - 'MSPH_EUREKA_USERNAME=${ENV_MSPH_EUREKA_USERNAME}'
      - 'MSPH_EUREKA_PASSWORD=${ENV_MSPH_EUREKA_PASSWORD}'
    depends_on:
      - msph-config-server

  msph-postgresql-client:
    container_name: msph-postgresql-client
    image: dpage/pgadmin4
    ports:
      - '${ENV_MSPH_PGADMIN_PORT}:80'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${ENV_MSPH_PGADMIN_USERNAME}'
      - 'PGADMIN_DEFAULT_PASSWORD=${ENV_MSPH_PGADMIN_PASSWORD}'
    volumes:
      - ./_db/servers.json:/pgadmin4/servers.json
    depends_on:
      msph-account-service-db:
        condition: service_healthy
      msph-auth-service-db:
        condition: service_healthy

  msph-vault:
    container_name: msph-vault
    image: vault:1.13.3
    ports:
      - '${ENV_MSPH_VAULT_PORT}:8200'
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - 'VAULT_ADDR=http://localhost:8200'
      - 'VAULT_DEV_ROOT_TOKEN_ID=${ENV_MSPH_VAULT_TOKEN}'
      - 'dev'
    cap_add:
      - IPC_LOCK

  msph-api-gateway:
    container_name: msph-api-gateway
    ports:
      - '${ENV_DOCKER_MSPH_API_GATEWAY_PORT}:8080'
    build:
      context: ./msph-api-gateway
      dockerfile: Dockerfile
      args:
        - 'OPEN_PORT=8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_DOCKER_EUREKA_PORT=8761'
      - 'MSPH_DOCKER_LANDING_PORT=${ENV_DOCKER_MSPH_LANDING_PORT}'
      - 'MSPH_DOCKER_CLIENT_PORT=${ENV_DOCKER_MSPH_API_GATEWAY_PORT}'
      - 'MSPH_SPRING_CONFIG_USERNAME=${ENV_DOCKER_MSPH_SPRING_CONFIG_USERNAME}'
      - 'MSPH_SPRING_CONFIG_PASSWORD=${ENV_DOCKER_MSPH_SPRING_CONFIG_PASSWORD}'
      - 'MSPH_EUREKA_USERNAME=${ENV_MSPH_EUREKA_USERNAME}'
      - 'MSPH_EUREKA_PASSWORD=${ENV_MSPH_EUREKA_PASSWORD}'
    depends_on:
      - msph-config-server
      - msph-discovery-server

  # START ACCOUNT SERVICE

  msph-account-service-db:
    extends:
      file: ./msph-account-service/docker-compose.yml
      service: msph-account-service-db-template

  msph-account-service:
    extends:
      file: ./msph-account-service/docker-compose.yml
      service: msph-account-service-template
    depends_on:
      - msph-config-server
      - msph-discovery-server
      - msph-api-gateway
      - msph-account-service-db

  # END ACCOUNT SERVICE
  # START AUTH SERVICE

  msph-auth-service-db:
    extends:
      file: ./msph-auth-service/docker-compose.yml
      service: msph-auth-service-db-template

  msph-auth-service:
    extends:
      file: ./msph-auth-service/docker-compose.yml
      service: msph-auth-service-template
    depends_on:
      - msph-config-server
      - msph-discovery-server
      - msph-api-gateway
      - msph-auth-service-db

  # END AUTH SERVICE
  # START MISC SERVICE

  msph-misc-service:
    extends:
      file: ./msph-misc-service/docker-compose.yml
      service: msph-misc-service-template
    depends_on:
      - msph-config-server
      - msph-discovery-server
      - msph-api-gateway

  # END MISC SERVICE
