version: '3.8'

name: moonsphere-infra

services:
  msph-config-server:
    container_name: msph-config-server
    ports:
      - '5160:8888'
    build:
      context: ./msph-config-server
      dockerfile: Dockerfile
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_VAULT_ROOT_TOKEN=${MSPH_VAULT_ROOT_TOKEN}'
      - 'MSPH_SPRING_CONFIG_USERNAME=${MSPH_SPRING_CONFIG_USERNAME}'
      - 'MSPH_SPRING_CONFIG_PASSWORD=${MSPH_SPRING_CONFIG_PASSWORD}'

  msph-discovery-server:
    container_name: msph-discovery-server
    ports:
      - '5161:8761'
    build:
      context: ./msph-discovery-server
      dockerfile: Dockerfile
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_VAULT_ROOT_TOKEN=${MSPH_VAULT_ROOT_TOKEN}'
      - 'MSPH_SPRING_CONFIG_USERNAME=${MSPH_SPRING_CONFIG_USERNAME}'
      - 'MSPH_SPRING_CONFIG_PASSWORD=${MSPH_SPRING_CONFIG_PASSWORD}'
    depends_on:
      - msph-vault
      - msph-config-server

  msph-postgresql-client:
    container_name: msph-postgresql-client
    image: dpage/pgadmin4
    ports:
      - '5162:80'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${MSPH_PGADMIN_USERNAME}'
      - 'PGADMIN_DEFAULT_PASSWORD=${MSPH_PGADMIN_PASSWORD}'
    volumes:
      - ./_db/servers.json:/pgadmin4/servers.json
    depends_on:
      msph-account-service-db:
        condition: service_healthy
      msph-auth-service-db:
        condition: service_healthy

  msph-vault:
    container_name: msph-vault
    image: hashicorp/vault
    ports:
      - '${MSPH_DEV_VAULT_PORT}:8200'
    volumes:
      - ./vault/data:/vault/data:rw
      - ./_vault:/vault/config
    environment:
      - 'VAULT_ADDR=http://127.0.0.1:8200'
      - 'VAULT_TOKEN=${MSPH_VAULT_ROOT_TOKEN}'
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl

  msph-api-gateway:
    container_name: msph-api-gateway
    ports:
      - '5055:8080'
    build:
      context: ./msph-api-gateway
      dockerfile: Dockerfile
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_DOCKER_LANDING_PORT=${MSPH_DOCKER_LANDING_PORT}'
      - 'MSPH_DOCKER_CLIENT_PORT=${MSPH_DOCKER_CLIENT_PORT}'
      - 'MSPH_VAULT_ROOT_TOKEN=${MSPH_VAULT_ROOT_TOKEN}'
      - 'MSPH_SPRING_CONFIG_USERNAME=${MSPH_SPRING_CONFIG_USERNAME}'
      - 'MSPH_SPRING_CONFIG_PASSWORD=${MSPH_SPRING_CONFIG_PASSWORD}'
    depends_on:
      - msph-config-server
      - msph-discovery-server

  msph-account-service-db:
    extends:
      file: ./msph-account-service/docker-compose.yml
      service: msph-account-service-db-template

  msph-auth-service-db:
    extends:
      file: ./msph-auth-service/docker-compose.yml
      service: msph-auth-service-db-template

  msph-account-service:
    extends:
      file: ./msph-account-service/docker-compose.yml
      service: msph-account-service-template
    depends_on:
      - msph-config-server
      - msph-discovery-server
      - msph-api-gateway
      - msph-account-service-db

  msph-auth-service:
    extends:
      file: ./msph-auth-service/docker-compose.yml
      service: msph-auth-service-template
    depends_on:
      - msph-config-server
      - msph-discovery-server
      - msph-api-gateway
      - msph-auth-service-db

  msph-misc-service:
    extends:
      file: ./msph-misc-service/docker-compose.yml
      service: msph-misc-service-template
    depends_on:
      - msph-config-server
      - msph-discovery-server
      - msph-api-gateway
