version: '3.8'

name: moonsphere-infra

services:
  msph-config-server:
    container_name: msph-config-server
    ports:
      - '5160:8888'
    image: milosz08/msph-config-server:latest
    pull_policy: always
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_VAULT_ROOT_TOKEN=${MSPH_VAULT_ROOT_TOKEN}'
      - 'MSPH_SPRING_CONFIG_USERNAME=${MSPH_SPRING_CONFIG_USERNAME}'
      - 'MSPH_SPRING_CONFIG_PASSWORD=${MSPH_SPRING_CONFIG_PASSWORD}'

  msph-discovery-server:
    container_name: msph-discovery-server
    ports:
      - '5161:8761'
    image: milosz08/msph-discovery-server:latest
    pull_policy: always
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_VAULT_ROOT_TOKEN=${MSPH_VAULT_ROOT_TOKEN}'
      - 'MSPH_SPRING_CONFIG_USERNAME=${MSPH_SPRING_CONFIG_USERNAME}'
      - 'MSPH_SPRING_CONFIG_PASSWORD=${MSPH_SPRING_CONFIG_PASSWORD}'
    depends_on:
      - msph-vault
      - msph-config-server

  msph-postgresql-db:
    container_name: msph-postgresql-db
    image: postgres:15.4-alpine
    ports:
      - '7500:5432'
    environment:
      - 'POSTGRES_USER=${MSPH_POSTGRES_USERNAME}'
      - 'POSTGRES_PASSWORD=${MSPH_POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=postgres'
    volumes:
      - ./_db/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./_db/postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 120

  msph-postgresql-client:
    container_name: msph-postgresql-client
    image: dpage/pgadmin4
    ports:
      - '5162:80'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${MSPH_PGADMIN_USERNAME}'
      - 'PGADMIN_DEFAULT_PASSWORD=${MSPH_PGADMIN_PASSWORD}'
    volumes:
      - ./_db/servers.json:/pgadmin4/servers.json
    depends_on:
      msph-postgresql-db:
        condition: service_healthy

  msph-mailhog:
    container_name: msph-mailhog
    image: mailhog/mailhog
    ports:
      - '${MSPH_DEV_MAILHOG_PORT}:1025'
      - '${MSPH_DEV_MAILHOG_CLIENT_PORT}:8025'
    environment:
      - 'MH_STORAGE=maildir'
      - 'MH_MAILDIR_PATH=/home/mailhog'
    volumes:
      - ./_mail/mailhog-volume:/home/mailhog
      - ./_mail/mailhog.conf:/etc/supervisor/conf.d
      - ./_mail/mailhog-auth.txt:/etc/mailhog-auth.txt

  msph-vault:
    container_name: msph-vault
    image: hashicorp/vault
    ports:
      - '${MSPH_DEV_VAULT_PORT}:8200'
    volumes:
      - ./vault/data:/vault/data:rw
      - ./_vault:/vault/config
      - ./.env:/.env
    environment:
      - 'VAULT_ADDR=http://127.0.0.1:8200'
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl

  msph-api-gateway:
    container_name: msph-api-gateway
    ports:
      - '5055:8080'
    image: milosz08/msph-api-gateway:latest
    pull_policy: always
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_DOCKER_LANDING_PORT=${MSPH_DOCKER_LANDING_PORT}'
      - 'MSPH_DOCKER_CLIENT_PORT=${MSPH_DOCKER_CLIENT_PORT}'
      - 'MSPH_VAULT_ROOT_TOKEN=${MSPH_VAULT_ROOT_TOKEN}'
      - 'MSPH_SPRING_CONFIG_USERNAME=${MSPH_SPRING_CONFIG_USERNAME}'
      - 'MSPH_SPRING_CONFIG_PASSWORD=${MSPH_SPRING_CONFIG_PASSWORD}'
    depends_on:
      - msph-config-server
      - msph-discovery-server

  msph-account-service:
    extends:
      file: ./msph-account-service/docker-compose.yml
      service: msph-account-service-template
    depends_on:
      - msph-config-server
      - msph-discovery-server
      - msph-api-gateway
      - msph-postgresql-db

  msph-auth-service:
    extends:
      file: ./msph-auth-service/docker-compose.yml
      service: msph-auth-service-template
    depends_on:
      - msph-config-server
      - msph-discovery-server
      - msph-api-gateway
      - msph-postgresql-db

  msph-misc-service:
    extends:
      file: ./msph-misc-service/docker-compose.yml
      service: msph-misc-service-template
    depends_on:
      - msph-config-server
      - msph-discovery-server
      - msph-api-gateway
