version: '3.8'

name: moonsphere-infra

services:
  msph-misc-service:
    container_name: msph-misc-service
    ports:
      - '7512:8080'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - 'OPEN_PORT=8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_DOCKER_EUREKA_PORT=8761'
    depends_on:
      - msph-config-server
      - msph-discovery-server
      - msph-api-gateway

  msph-config-server:
    extends:
      file: ../docker-compose.yml
      service: msph-config-server

  msph-discovery-server:
    extends:
      file: ../docker-compose.yml
      service: msph-discovery-server

  msph-api-gateway:
    extends:
      file: ../docker-compose.yml
      service: msph-api-gateway
