version: '3.8'

name: moonsphere-infra

services:
  msph-misc-service-template:
    container_name: msph-misc-service
    ports:
      - '8080'
    build:
      context: ./msph-misc-service
      dockerfile: Dockerfile
      args:
        - 'OPEN_PORT=8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_DOCKER_EUREKA_PORT=8761'
      - 'MSPH_SPRING_CONFIG_USERNAME=${ENV_DOCKER_MSPH_SPRING_CONFIG_USERNAME}'
      - 'MSPH_SPRING_CONFIG_PASSWORD=${ENV_DOCKER_MSPH_SPRING_CONFIG_PASSWORD}'
      - 'MSPH_CAPTCHA_SECRETKEY=${MSPH_CAPTCHA_SECRETKEY}'
      - 'MSPH_EUREKA_USERNAME=${ENV_MSPH_EUREKA_USERNAME}'
      - 'MSPH_EUREKA_PASSWORD=${ENV_MSPH_EUREKA_PASSWORD}'
      - 'MSPH_CAPTCHA_DEV_SITEKEY=${MSPH_CAPTCHA_DEV_SITEKEY}'
