version: '3.8'

name: moonsphere-infra

services:
  msph-misc-service-template:
    container_name: msph-misc-service
    ports:
      - '8080'
    build:
      context: ./msph-misc-service
      dockerfile: Dockerfile
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'MSPH_VAULT_ROOT_TOKEN=${MSPH_VAULT_ROOT_TOKEN}'
      - 'MSPH_SPRING_CONFIG_USERNAME=${MSPH_SPRING_CONFIG_USERNAME}'
      - 'MSPH_SPRING_CONFIG_PASSWORD=${MSPH_SPRING_CONFIG_PASSWORD}'
