server:
  port: 8888

spring:
  cloud:
    vault:
      uri: http://msph-vault:8200
  security:
    user:
      name: ${MSPH_SPRING_CONFIG_USERNAME}
      password: ${MSPH_SPRING_CONFIG_PASSWORD}
  config:
    import: optional:vault://
