server:
  servlet:
    context-path: /config

spring:
  application:
    name: msph-config-server
  cloud:
    vault:
      token: ${MSPH_VAULT_ROOT_TOKEN}
      authentication: TOKEN
      scheme: http
      kv:
        backend: moonsphere
        default-context: msph-common
        application-name: ${spring.application.name}
    config:
      server:
        git:
          uri: https://github.com/moonsphere-systems/moonsphere-infra-cloud-config
          username: ${V_SPRING_CONFIG_GIT_USERNAME}
          password: ${V_SPRING_CONFIG_GIT_TOKEN}
          default-label: 'master'
  banner:
    location: classpath:spring/banner.txt

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
