server:
  port: 6160
spring:
  profiles:
    active: native
  application:
    name: msph-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
