server:
  port: ${MSPH_DEV_CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: msph-config-server
  cloud:
    config:
      token:
    vault:
      uri: http://localhost:${MSPH_DEV_VAULT_PORT}
  config:
    import: optional:vault://
