eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:6161/eureka

server:
  port: 6162

spring:
  application:
    name: msph-account-service

management:
  tracing:
    sampling:
      probability: 1.0
