spring:
  config:
    import: optional:configserver:http://msph-config-server:8888/config
  cloud:
    config:
      username: ${MSPH_SPRING_CONFIG_USERNAME}
      password: ${MSPH_SPRING_CONFIG_PASSWORD}
