version: '3.8'

services:
  vsph-m-sphere-service-template:
    container_name: vsph-m-sphere-service
    ports:
      - '8080'
    image: milosz08/vsph-m-sphere-service:latest
    pull_policy: always
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'VSPH_VAULT_ROOT_TOKEN=${VSPH_VAULT_ROOT_TOKEN}'
      - 'VSPH_SPRING_CONFIG_USERNAME=${VSPH_SPRING_CONFIG_USERNAME}'
      - 'VSPH_SPRING_CONFIG_PASSWORD=${VSPH_SPRING_CONFIG_PASSWORD}'
      - 'VSPH_KAFKA_CERTS_CONTAINER=/kafka/cert'
    volumes:
      - ../.volumes/kafka/secrets/local/kafka.keystore.jks:/kafka/cert/kafka.keystore.jks
      - ../.volumes/kafka/secrets/local/kafka.truststore.jks:/kafka/cert/kafka.truststore.jks
