spring:
  config:
    import:
      - optional:vault://
      - optional:configserver:http://msph-config-server:8888/config
  cloud:
    vault:
      uri: http://msph-vault:8200
    config:
      username: ${MSPH_SPRING_CONFIG_USERNAME}
      password: ${MSPH_SPRING_CONFIG_PASSWORD}
