spring:
  application:
    name: vsph-m-chat-service
  cloud:
    vault:
      token: ${VSPH_VAULT_ROOT_TOKEN}
      authentication: TOKEN
      kv:
        backend: visphere
        default-context: vsph-common
        application-name: ${spring.application.name}
